### ISSUE TITLE
add installation & dev instructions to the README file

### ISSUE THREAD

**Issue by phivk** [FitzwilliamMuseum/amor-fitz-frontend#12]
would be nice to have instructions for local installation and development. 

I came as far as installing via composer and npm, but when I run `$ php artisan serve` I am still getting components that display a 500 server error. 

I'm not sure if this is something I can easily solve locally without requiring API credentials?

**Comment by portableant** [comment]
That's coming shortly! Need more hours in the day. 
npm install && npm run dev in root folder should fix your errors.
