### ISSUE TITLE
purple text color breaks with colour scheme

### ISSUE THREAD

**Issue by phivk** [FitzwilliamMuseum/amor-fitz-frontend#4]
Some heading use a purple color which is outside of the [colour scheme](https://phivk.com/fitz-hayley/?path=/story/utils-colourpalette--regular):

<img width="581" alt="67F5BE3E-46C2-4C88-97E6-D704DD1ACB53-873-00008BEE6AB9F632" src="https://user-images.githubusercontent.com/902958/144902669-9369f22c-9886-4e4e-871d-3aced2379923.png">

I'd recommend using the berry color instead.

**Comment by portableant** [comment]
Only just saw this and already rolled out fix, so will close #5 as well.
