### ISSUE TITLE
TheHeader Title uses sans-serif font

### ISSUE THREAD

**Issue by phivk** [FitzwilliamMuseum/amor-fitz-frontend#6]
TheHeader Title could use the serif font Baskerville as proposed in [the design](https://phivk.com/fitz-hayley/?path=/story/theheader--regular):

<img width="1792" alt="1BB22198-722F-4F5A-BBE6-4B7654CEB22A-873-00009986CDA5B799" src="https://user-images.githubusercontent.com/902958/144994630-468ec2a8-6eb1-418c-a427-0f2fbf27969b.png">

In fact I'd recommend all headings to use a Baskerville (as proposed in the design), but this main title is especially significant.

Furthermore, I believe rendering this title in a serif font sets it apart from the other UI texts and thereby removes the need to surround it by 'single quotes' (single quotes look weird in a NavBar title)

**Comment by portableant** [comment]
Closed in 8efd65a288505632df332e0889a70f61974d23f1
